# Generated by Django 5.0.7 on 2024-07-11 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pasillo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bodega',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=30)),
                ('codigo_postal', models.IntegerField()),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('cargo', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pago',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_pedido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('fecha_estimada', models.DateField()),
            ],
            options={
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_orden', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_orden',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.ForeignKey(db_column='ciudad_id_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ciudad')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(db_column='cliente_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
            ],
            options={
                'db_table': 'cuenta_cliente',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cuenta_cliente', models.ForeignKey(db_column='cuenta_cliente_email', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cuentacliente')),
                ('empleado', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'detalle_orden',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('nombre_proveedor', models.CharField(max_length=40)),
                ('apellido_proveedor', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('oferta', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('empleado', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'oferta',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresencial',
            fields=[
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('orden_compra', models.OneToOneField(db_column='orden_compra_id_orden', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.ordencompra')),
            ],
            options={
                'db_table': 'solicitud_presencial',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='detalle_orden',
            field=models.ForeignKey(db_column='detalle_orden_id_detalle_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='core.detalleorden'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_pago',
            field=models.ForeignKey(db_column='estado_pago_id_estado_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadopago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_pedido',
            field=models.ForeignKey(db_column='estado_pedido_id_estado_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadopedido'),
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_estanteria', models.IntegerField()),
                ('bodega', models.ForeignKey(db_column='bodega_id_bodega', on_delete=django.db.models.deletion.DO_NOTHING, to='core.bodega')),
            ],
            options={
                'db_table': 'pasillo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('oferta', models.CharField(max_length=1)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('marca', models.ForeignKey(db_column='marca_id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='core.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('pasillo', models.ForeignKey(db_column='pasillo_id_pasillo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.pasillo')),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'estanteria',
            },
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(db_column='producto_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(db_column='region_id_region', on_delete=django.db.models.deletion.DO_NOTHING, to='core.region'),
        ),
        migrations.CreateModel(
            name='CuentaEmpleado',
            fields=[
                ('usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=20)),
                ('empleado', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
                ('rol', models.ForeignKey(db_column='rol_id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='core.rol')),
            ],
            options={
                'db_table': 'cuenta_empleado',
            },
        ),
        migrations.CreateModel(
            name='SolicitudProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('nombre_categoria', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('nombre_marca', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=30, null=True)),
                ('empleado', models.ForeignKey(db_column='empleado_rut', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'solicitud_productos',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_orden',
            field=models.ForeignKey(db_column='tipo_orden_id_tipo_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipoorden'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_pago',
            field=models.ForeignKey(db_column='tipo_pago_id_tipo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipopago'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('producto', models.ForeignKey(db_column='producto_id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'valoracion',
            },
        ),
    ]
